# Generated by Django 5.1.3 on 2026-06-01 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("unite_mesure", models.CharField(max_length=20)),
                ("seuil_alerte", models.PositiveIntegerField()),
                (
                    "actif",
                    models.BooleanField(
                        default=True, verbose_name="Actif / Visible formulaire stock"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie de stock",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("categorie", models.CharField(max_length=100)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="LotPoules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="", max_length=100)),
                ("date_arrivee", models.DateField()),
                ("effectif", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Poulailler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="", max_length=100)),
                ("effectif_initial", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AlertesStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_alerte", models.DateTimeField(auto_now_add=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[("warning", "⚠️"), ("critical", "🚨")], max_length=20
                    ),
                ),
                ("message", models.TextField()),
                ("acquittee", models.BooleanField(default=False)),
                ("date_acquittement", models.DateTimeField(blank=True, null=True)),
                (
                    "acquittee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.categoriestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte stock",
                "ordering": ["-date_alerte"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "📥 Entrée"),
                            ("sortie", "📤 Sortie"),
                            ("ajustement", "🔧"),
                            ("perte", "🗑️"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("fournisseur_client", models.CharField(blank=True, max_length=200)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="gestion.categoriestock",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MouvementCheptel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("achat", "🛒 Achat / Renouvellement"),
                            ("transfert_in", "📥 Transfert entrant"),
                            ("transfert_out", "📤 Transfert sortant"),
                            ("reforme", "🔄 Réforme / Vente cheptel"),
                            ("mortalite", "🪦 Mortalité exceptionnelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nombre_poules",
                    models.IntegerField(help_text="Nombre de poules concernées"),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Ex: Lot acheté à X, transfert Bât. C...",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_cheptel",
                        to="gestion.poulailler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de cheptel",
                "verbose_name_plural": "Mouvements de cheptel",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Collecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("plateaux", models.IntegerField(default=0)),
                ("oeufs_unites", models.IntegerField(default=0)),
                ("total_oeufs", models.IntegerField(default=0)),
                ("oeufs_casses", models.IntegerField(default=0)),
                (
                    "poulailler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.poulailler",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOeufs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("nombre_oeufs", models.IntegerField()),
                ("oeufs_casses", models.IntegerField(default=0)),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.poulailler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("unite", models.CharField(default="unités", max_length=20)),
                (
                    "seuil_alerte",
                    models.IntegerField(
                        default=0, help_text="Quantité minimum déclenchant une alerte"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="gestion.categoriestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit / Article",
                "verbose_name_plural": "Produits",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Sante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("traitement", models.CharField(max_length=200)),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.poulailler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SanteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type_sante",
                    models.CharField(
                        choices=[
                            ("vaccin", "Vaccin"),
                            ("traitement", "Traitement"),
                            ("vet", "Vétérinaire"),
                        ],
                        max_length=50,
                    ),
                ),
                ("produit", models.CharField(blank=True, max_length=100)),
                (
                    "cout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "poulailler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.poulailler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SortiePoules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("nombre", models.PositiveIntegerField()),
                (
                    "type_sortie",
                    models.CharField(
                        choices=[
                            ("mortalite", "🪦 Mortalité"),
                            ("vente", "💰 Vente improductive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prix_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.poulailler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Client"
                    ),
                ),
                (
                    "type_vente",
                    models.CharField(
                        choices=[
                            ("oeufs", "🥚 Œufs"),
                            ("poules", "🐔 Poules"),
                            ("autres", "📦 Autres"),
                        ],
                        default="oeufs",
                        max_length=20,
                    ),
                ),
                ("unites", models.IntegerField(default=0)),
                (
                    "prix_plateau",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("paye", models.BooleanField(default=True)),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant payé (FCFA)",
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Reste à payer (FCFA)",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("comptant", "💵 Comptant"),
                            ("credit", "📝 Crédit"),
                            ("mobile", "📱 Mobile Money"),
                            ("cheque", "🧾 Chèque"),
                        ],
                        default="comptant",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "plateaux",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de plateaux (30 œufs)"
                    ),
                ),
                (
                    "reste_oeufs",
                    models.IntegerField(default=0, verbose_name="Œufs restants (0-29)"),
                ),
                (
                    "poulailler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.poulailler",
                        verbose_name="Bâtiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date"],
            },
        ),
    ]
