# Generated by Django 5.1.3 on 2026-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionoeufs",
            name="oeufs_unites",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionoeufs",
            name="plateaux",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productionoeufs",
            name="total_oeufs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productionoeufs",
            name="nombre_oeufs",
            field=models.IntegerField(default=0),
        ),
    ]
