# Generated by Django 5.1.3 on 2026-06-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_productionoeufs_oeufs_unites_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Collecte",
        ),
    ]
