# Generated by Django 5.1.3 on 2026-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_categoriestock_client_depense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="montant_restant",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Reste à payer (FCFA)",
            ),
        ),
    ]
