# Generated by Django 5.1.3 on 2026-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0006_produit"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriestock",
            name="actif",
            field=models.BooleanField(
                default=True, verbose_name="Actif / Visible formulaire stock"
            ),
        ),
    ]
