# Generated by Django 5.1.3 on 2026-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_categoriestock_actif"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="reste_oeufs",
            field=models.IntegerField(default=0, verbose_name="Œufs restants (0-29)"),
        ),
        migrations.AlterField(
            model_name="vente",
            name="plateaux",
            field=models.IntegerField(
                default=0, verbose_name="Nombre de plateaux (30 œufs)"
            ),
        ),
    ]
