"""
Django settings for dokaha project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g^_vti)w+vzudqeoq4qzh*+pm$o(l1$*0-nolsz2ea%zge(w3$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 🌐 ALLOWED_HOSTS pour développement local + réseau + mobile
import os

# =============================================================================
# 🔐 SÉCURITÉ & HÔTES AUTORISÉS (Development Local + Réseau + Mobile)
# =============================================================================

# ✅ Hosts autorisés (IP locale, localhost, et * pour dev)
ALLOWED_HOSTS = [
    'fane.pythonanywhere.com',  # ✅ Ton domaine en ligne
    'localhost',
    '127.0.0.1',
    '*'  # ✅ Pour le développement (à retirer en production réelle)
]

# ✅ Pour production HTTPS (PythonAnywhere)
SESSION_COOKIE_SECURE = True       # ← Changed from False
CSRF_COOKIE_SECURE = True          # ← Changed from False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_NAME = 'dokaha_sid'
SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# ⚠️ SUPPRIMER ou COMMENTER cette ligne (elle bloque les cookies sur HTTP/IP)
# SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

CSRF_TRUSTED_ORIGINS = [
    'https://fane.pythonanywhere.com',  # ✅ Ton domaine en ligne (HTTPS)
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://192.168.1.9:8000',
]

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# =============================================================================
# 🍪 COOKIES & SESSIONS (CORRECTION DU BUG DE CONNEXION SUR IP/HTTP)
# =============================================================================
# ⚠️ Ces réglages sont pour le DÉVELOPPEMENT uniquement (HTTP, IP locale).
# En production (HTTPS), il faudra les inverser.

# Autoriser les cookies de session sur HTTP (non sécurisé)
SESSION_COOKIE_SECURE = False          # ← True en production HTTPS seulement
CSRF_COOKIE_SECURE = False             # ← True en production HTTPS seulement

# SameSite=Lax permet l'envoi des cookies dans les requêtes POST normales
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Nom des cookies (optionnel, mais évite les conflits si plusieurs projets Django)
SESSION_COOKIE_NAME = 'dokaha_sessionid'
CSRF_COOKIE_NAME = 'dokaha_csrftoken'

# Durée de session : 2 semaines (ajuste selon tes besoins)
SESSION_COOKIE_AGE = 1209600  # 14 jours en secondes

# =============================================================================
# 🌐 CROSS-ORIGIN POLICY (Évite les warnings COOP/COEP sur IP)
# =============================================================================
# Autorise l'ouverture de popups/fenêtres depuis la même origine
# SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# En développement, on désactive les redirections HTTPS forcées
SECURE_SSL_REDIRECT = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dokaha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dokaha.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# =============================================================================
# 🔐 REDIRECTION APRÈS CONNEXION
# =============================================================================
# Où rediriger l'utilisateur après un login réussi ?
LOGIN_REDIRECT_URL = 'dashboard'  # ← Nom de la route Django (name='dashboard')
LOGOUT_REDIRECT_URL = 'login'     # ← Où aller après déconnexion

# URL de login (pour que @login_required sache où rediriger)
LOGIN_URL = 'login'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
ALLOWED_HOSTS = ['fane.pythonanywhere.com', 'localhost', '127.0.0.1', '*']  # ← Vérifie qu'elle est bien là

