# Generated by Django 5.2.13 on 2026-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poulailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('A', 'Bâtiment A'), ('B', 'Bâtiment B'), ('C', 'Bâtiment C'), ('D', 'Bâtiment D'), ('E', 'Bâtiment E')], max_length=1, unique=True)),
                ('capacite', models.PositiveIntegerField(default=1000)),
                ('race', models.CharField(default='ISA Brown', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
