# Generated by Django 5.2.13 on 2026-04-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPoules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lot', models.CharField(max_length=50, verbose_name='Nom du lot')),
                ('race', models.CharField(default='ISA Brown', max_length=50, verbose_name='Race')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('age_arrivee_semaines', models.PositiveIntegerField(default=18, help_text="Âge en semaines à l'arrivée", verbose_name="Âge à l'arrivée (sem.)")),
                ('effectif_initial', models.PositiveIntegerField(verbose_name='Effectif initial')),
                ('mortalites', models.PositiveIntegerField(default=0, verbose_name='Mortalités')),
                ('vendues', models.PositiveIntegerField(default=0, verbose_name='Poules vendues')),
                ('poulailler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='gestion.poulailler', verbose_name='Poulailler')),
            ],
        ),
    ]
