# Generated by Django 5.2.13 on 2026-04-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_lotpoules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotpoules',
            name='age_arrivee_semaines',
            field=models.PositiveIntegerField(default=18, verbose_name="Âge à l'arrivée (sem.)"),
        ),
        migrations.AlterField(
            model_name='lotpoules',
            name='poulailler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='gestion.poulailler'),
        ),
        migrations.AlterField(
            model_name='lotpoules',
            name='race',
            field=models.CharField(default='ISA Brown', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductionOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de collecte')),
                ('nombre_oeufs', models.PositiveIntegerField(verbose_name='Total collectés')),
                ('oeufs_casses', models.PositiveIntegerField(default=0, verbose_name='Œufs cassés')),
                ('poulailler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='gestion.poulailler', verbose_name='Poulailler')),
            ],
            options={
                'verbose_name_plural': "Productions d'œufs",
                'ordering': ['-date'],
            },
        ),
    ]
