# Generated by Django 5.1.3 on 2026-04-30 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_alter_lotpoules_age_arrivee_semaines_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("unite_mesure", models.CharField(max_length=20)),
                ("seuil_alerte", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Catégorie de stock",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("categorie", models.CharField(max_length=100)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AlterModelOptions(
            name="productionoeufs",
            options={},
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="age_arrivee_semaines",
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="effectif_initial",
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="mortalites",
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="nom_lot",
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="poulailler",
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="race",
        ),
        migrations.RemoveField(
            model_name="lotpoules",
            name="vendues",
        ),
        migrations.RemoveField(
            model_name="poulailler",
            name="actif",
        ),
        migrations.RemoveField(
            model_name="poulailler",
            name="capacite",
        ),
        migrations.RemoveField(
            model_name="poulailler",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="poulailler",
            name="race",
        ),
        migrations.AddField(
            model_name="lotpoules",
            name="effectif",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lotpoules",
            name="nom",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="poulailler",
            name="effectif_initial",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lotpoules",
            name="date_arrivee",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="poulailler",
            name="nom",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="productionoeufs",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="productionoeufs",
            name="nombre_oeufs",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="productionoeufs",
            name="oeufs_casses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productionoeufs",
            name="poulailler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.poulailler"
            ),
        ),
        migrations.CreateModel(
            name="AlertesStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_alerte", models.DateTimeField(auto_now_add=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[("warning", "⚠️"), ("critical", "🚨")], max_length=20
                    ),
                ),
                ("message", models.TextField()),
                ("acquittee", models.BooleanField(default=False)),
                ("date_acquittement", models.DateTimeField(blank=True, null=True)),
                (
                    "acquittee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.categoriestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte stock",
                "ordering": ["-date_alerte"],
            },
        ),
        migrations.CreateModel(
            name="MouvementCheptel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("achat", "🛒 Achat / Renouvellement"),
                            ("transfert_in", "📥 Transfert entrant"),
                            ("transfert_out", "📤 Transfert sortant"),
                            ("reforme", "🔄 Réforme / Vente cheptel"),
                            ("mortalite", "🪦 Mortalité exceptionnelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nombre_poules",
                    models.IntegerField(help_text="Nombre de poules concernées"),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Ex: Lot acheté à X, transfert Bât. C...",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_cheptel",
                        to="gestion.poulailler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de cheptel",
                "verbose_name_plural": "Mouvements de cheptel",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "📥 Entrée"),
                            ("sortie", "📤 Sortie"),
                            ("ajustement", "🔧"),
                            ("perte", "🗑️"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("fournisseur_client", models.CharField(blank=True, max_length=200)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="gestion.categoriestock",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Sante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("traitement", models.CharField(max_length=200)),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.poulailler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SortiePoules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("nombre", models.PositiveIntegerField()),
                (
                    "type_sortie",
                    models.CharField(
                        choices=[
                            ("mortalite", "🪦 Mortalité"),
                            ("vente", "💰 Vente improductive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prix_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "poulailler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.poulailler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Client"
                    ),
                ),
                (
                    "type_vente",
                    models.CharField(
                        choices=[
                            ("oeufs", "🥚 Œufs"),
                            ("poules", "🐔 Poules"),
                            ("autres", "📦 Autres"),
                        ],
                        default="oeufs",
                        max_length=20,
                    ),
                ),
                ("plateaux", models.IntegerField(default=0)),
                ("unites", models.IntegerField(default=0)),
                (
                    "prix_plateau",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("paye", models.BooleanField(default=True)),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant payé (FCFA)",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("comptant", "💵 Comptant"),
                            ("credit", "📝 Crédit"),
                            ("mobile", "📱 Mobile Money"),
                            ("cheque", "🧾 Chèque"),
                        ],
                        default="comptant",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "poulailler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.poulailler",
                        verbose_name="Bâtiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date"],
            },
        ),
    ]
