# Generated by Django 5.1.3 on 2026-05-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_vente_montant_restant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("unite", models.CharField(default="unités", max_length=20)),
                (
                    "seuil_alerte",
                    models.IntegerField(
                        default=0, help_text="Quantité minimum déclenchant une alerte"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="gestion.categoriestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit / Article",
                "verbose_name_plural": "Produits",
                "ordering": ["categorie", "nom"],
            },
        ),
    ]
